### ISSUE TITLE
make: *** [Makefile:183: sub-make] Error 2

### ISSUE THREAD

**Issue by STTecCEO** [freak07/Kirisakura_Sagami#1]
Hello, I'm trying to compile this source code but it always fails in the same place with the error message "make: *** [Makefile:183: sub-make] Error 2". I'm using the clang 14.0.7 compiler. Do you know if there is anything I might be missing?
![image](https://user-images.githubusercontent.com/35169436/236180805-826d493f-6549-488b-85c3-3a3cd70a8517.png)
![image](https://user-images.githubusercontent.com/35169436/236246515-d6701ec7-7f0a-47a1-856d-46ffde185d68.png)

**Comment by huchenz1** [comment]
Could you please tell me how to fix it?  Do I need to change the symbol link pinctrl-utils.h?  Thank you!

**Comment by STTecCEO** [comment]
> Could you please tell me how to fix it? Do I need to change the symbol link pinctrl-utils.h? Thank you!

https://developer.sony.com/zh/file/download/open-source-archive-for-61-2-a-0-382/ 把官方源码解压丢你最顶头的目录里 或者数数你缺的头文件源路径前面有多少个路径符

**Comment by huchenz1** [comment]
> > Could you please tell me how to fix it? Do I need to change the symbol link pinctrl-utils.h? Thank you!
> 
> https://developer.sony.com/zh/file/download/open-source-archive-for-61-2-a-0-382/ 把官方源码解压丢你最顶头的目录里 或者数数你缺的头文件源路径前面有多少个路径符

解决了，感谢！我刚开始就很奇怪那个msm5.4的文件夹在哪，然后把那个软连接指向driver下面相同路径的文件了，就还是报错 😂
